
test_run: False
output_dir: "cot-parser-checker"
models:
# - "google:gemini-2.0-flash-thinking-exp"
# - "openai:gpt-4o"
# - "openai:gpt-4o-mini"
# - "google:gemini-2.0-flash-exp"
# - "together:Qwen/QwQ-32B-Preview"
# - "together:meta-llama/Llama-3.3-70B-Instruct-Turbo"
 - "anthropic:claude-3-5-sonnet-latest"
# - "anthropic:claude-3-5-haiku-latest"
# - "together:meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo-128K"
# - "together:meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo"
# - "together:Qwen/Qwen2.5-72B-Instruct-Turbo"
solver:
  #system_prompt: "You are a math expert." 
  parse_feedback: True
  check_feedback: True
  error_string: "The solution parser encountered the following error:\n{error}\nPlease format your reply accurately."
  max_feedback_rounds: 2
  formatting_prefix: "Format your reply as follows:"
inference:
  temperature: 1.0 
  top_p: 0.9 
  max_tokens: 16000
  concurrent_requests: 10 
  timeout: 2000
problems:
  - ".*"
n_variations: 4
